version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: transactions-db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong@Password123
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - transactions-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transactions-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=TransactionsDb;User Id=sa;Password=YourStrong@Password123;TrustServerCertificate=True;
    ports:
      - "5000:80"
    depends_on:
      - sqlserver
    networks:
      - transactions-network

volumes:
  sqlserver-data:

networks:
  transactions-network:
    driver: bridge